### ISSUE TITLE
Timing

### ISSUE THREAD

**Issue by mroeckl** [entrusc/Pi-RC-Switch#3]
I tried to use the Pi-RC-Switch on a Raspberry Pi (Model B) with Raspbian OS but it seems that the pulse length is too long. It is about twice as long as required. It seems to be a problem of Pi4J (1.0-RC) because I experienced that the delay for enabling/disabling pins takes too long. I measured the times with an oscilloscope.

Has someone experienced the same problem? Or could someone use Pi-RC-Switch on the same setup?

Thank you very much for your support.

**Comment by entrusc** [comment]
Hmm. I use this library activly on a Pi Model B and everything works fine. But I'm using the 0.0.5 version of pi4j (as required by the Pi-RC-Switch library's pom). Maybe you should give that version a try?

**Comment by mroeckl** [comment]
Thanks. I tried it with version 0.0.5 and it is working. Seems that the newest release is broken. Thank you for your support.
