### ISSUE TITLE
OpenHAB Integration

### ISSUE THREAD

**Issue by mroeckl** [entrusc/Pi-RC-Switch#4]
Would you be interested in integrating your code into OpenHAB as a binding? I already prepared a prototype implementation and it seems to work fine.

**Comment by entrusc** [comment]
Sure. OpenHAB sounds like an interesting project. I guess I'd need to implement some OSGi interface, add some descriptors to the pom file? Can you point me to some documentation or tutorial, so I know what exactly to add to Pi-RC-Switch to make it compatible with OpenHAB?

**Comment by mroeckl** [comment]
Awesome. We could use your implementation for controlling the switches as it is. I already prepared everything needed to use it as an OpenHAB binding. Let me raise a request in the OpenHAB community. I will get back to you.

**Comment by patrickse** [comment]
Any news on this?

**Comment by mroeckl** [comment]
I triggered a pull request on OpenHAB. Now, I received feedback that the license of your code (GPL) is not compatible to the license of OpenHAB which is EPL (see [pull request](https://github.com/openhab/openhab/pull/2567/files#r43589861)). @entrusc, what is your opinion on that? Would you mind changing the license of your class which I added to the OpenHAB project to EPL?

**Comment by entrusc** [comment]
I certainly would. But the problem is that this is a port of another library that is under LGPL, so I'm not sure if I'm legally allowed to do that.
